# Assignment 7 - oct 18th 2022

In [ ]:
import numpy as np
import pandas as pd

In [71]:
iris = pd.read_csv(r"C:\Users\Venkatesh Yeturi\OneDrive\Desktop\Class pdfs\Machine Learning\all lab assignments\Iris.csv")

In [72]:
iris_setosa = iris[iris['Species']=='Iris-setosa']
iris_versicolor = iris[iris['Species']=='Iris-versicolor']
iris_virginica = iris[iris['Species']=='Iris-virginica']

In [73]:
iris_setosa = iris_setosa.drop(columns=['Species','Id'])
iris_versicolor = iris_versicolor.drop(columns=['Species','Id'])
iris_virginica = iris_virginica.drop(columns=['Species','Id'])

In [119]:
iris_setosa = np.array(iris_setosa)
iris_versicolor = np.array(iris_versicolor)
iris_virginica = np.array(iris_virginica)

In [75]:
iris_setosa_train = iris_setosa[:35]

In [76]:
iris_setosa_test = iris_setosa[35:]

In [117]:
iris_setosa_train_mean = iris_setosa_train.mean(axis=0)
iris_setosa_train_mean

array([5.04571429, 3.46857143, 1.47714286, 0.24      ])

In [78]:
iris_versicolor_train = iris_versicolor[:35]

In [79]:
iris_versicolor_test = iris_versicolor[35:]

In [80]:
iris_versicolor_train_mean = iris_versicolor_train.mean(axis=0)

In [81]:
iris_virginica_train = iris_virginica[:35]

In [82]:
iris_virginica_test = iris_virginica[35:]

In [83]:
iris_virginica_train_mean = iris_virginica_train.mean(axis=0)

In [84]:
iris_virginica_train_mean

array([6.61714286, 2.93714286, 5.62571429, 1.97714286])

In [85]:
cov_setosa = (iris_setosa_train - iris_setosa_train_mean).T @ (iris_setosa_train - iris_setosa_train_mean)

In [86]:
cov_setosa

array([[ 4.46685714,  3.49028571,  0.46657143,  0.506     ],
       [ 3.49028571,  4.77542857, -0.04514286,  0.494     ],
       [ 0.46657143, -0.04514286,  1.02171429,  0.162     ],
       [ 0.506     ,  0.494     ,  0.162     ,  0.364     ]])

In [87]:
cov_versicolor = (iris_versicolor_train - iris_versicolor_train_mean).T @ (iris_versicolor_train - iris_versicolor_train_mean)

In [88]:
cov_versicolor

array([[9.68742857, 3.24942857, 6.17571429, 1.90714286],
       [3.24942857, 3.47542857, 2.91571429, 1.53714286],
       [6.17571429, 2.91571429, 7.60285714, 2.74857143],
       [1.90714286, 1.53714286, 2.74857143, 1.58571429]])

In [89]:
cov_virginica = (iris_virginica_train - iris_virginica_train_mean ).T @ (iris_virginica_train - iris_virginica_train_mean)

In [90]:
cov_virginica

array([[16.46971429,  4.41771429, 12.95457143,  1.60371429],
       [ 4.41771429,  4.16171429,  3.23657143,  1.61971429],
       [12.95457143,  3.23657143, 12.50685714,  2.02057143],
       [ 1.60371429,  1.61971429,  2.02057143,  2.54171429]])

In [116]:
inv_cov_setosa = np.linalg.inv(cov_setosa)
inv_cov_setosa

array([[ 0.60334672, -0.42970595, -0.27327281, -0.13392447],
       [-0.42970595,  0.55411268,  0.26385371, -0.27210098],
       [-0.27327281,  0.26385371,  1.19614962, -0.51056025],
       [-0.13392447, -0.27210098, -0.51056025,  3.52992974]])

In [92]:
inv_cov_versicolor = np.linalg.inv(cov_versicolor)

In [93]:
inv_cov_virginica = np.linalg.inv(cov_virginica)

In [94]:
inv_cov_virginica

array([[ 0.42942789, -0.20188941, -0.42402394,  0.1947875 ],
       [-0.20188941,  0.45448729,  0.13505956, -0.26960705],
       [-0.42402394,  0.13505956,  0.5219208 , -0.23343414],
       [ 0.1947875 , -0.26960705, -0.23343414,  0.62791214]])

In [120]:
def gaussian(x, mean, inv_cov):
    return (2*3.14)**(-2) * np.exp( -0.5 * (x-mean).T @ inv_cov @ (x-mean))

In [121]:
true_setosa = 0
true_versicolor =0
true_virginica = 0
false_setosa=0
false_versicolor=0
false_virginica=0

In [122]:
for x in iris_setosa_test:
    prob_setosa = gaussian(x,iris_setosa_train_mean,inv_cov_setosa)
    prob_versicolor = gaussian(x,iris_versicolor_train_mean,inv_cov_versicolor)
    prob_virginica = gaussian(x,iris_virginica_train_mean,inv_cov_virginica)
    if(prob_setosa>prob_versicolor and prob_setosa>prob_virginica):
        true_setosa = true_setosa+1
    elif(prob_versicolor>prob_setosa and prob_versicolor>prob_virginica):
        false_versicolor = false_versicolor+1
    else:
        false_virginica = false_virginica+1
print(true_setosa,false_versicolor,false_virginica)

15 0 0


In [123]:
for x in iris_versicolor_test:
    prob_setosa = gaussian(x,iris_setosa_train_mean,inv_cov_setosa)
    prob_versicolor = gaussian(x,iris_versicolor_train_mean,inv_cov_versicolor)
    prob_virginica = gaussian(x,iris_virginica_train_mean,inv_cov_virginica)
    if(prob_setosa>prob_versicolor and prob_setosa>prob_virginica):
        false_setosa = false_setosa+1
    elif(prob_versicolor>prob_setosa and prob_versicolor>prob_virginica):
        true_versicolor = true_versicolor+1
    else:
        false_virginica = false_virginica+1
print(false_setosa,true_versicolor,false_virginica)

0 15 0


In [124]:
for x in iris_virginica_test:
    prob_setosa = gaussian(x,iris_setosa_train_mean,inv_cov_setosa)
    prob_versicolor = gaussian(x,iris_versicolor_train_mean,inv_cov_versicolor)
    prob_virginica = gaussian(x,iris_virginica_train_mean,inv_cov_virginica)
    if(prob_setosa>prob_versicolor and prob_setosa>prob_virginica):
        false_setosa = false_setosa+1
    elif(prob_versicolor>prob_setosa and prob_versicolor>prob_virginica):
        false_versicolor = false_versicolor+1
    else:
        true_virginica = true_virginica+1
print(false_setosa,false_versicolor,true_virginica)

0 0 15


In [126]:
confusion_matrix = np.array([[true_setosa,false_versicolor,false_virginica],
                           [false_setosa,true_versicolor,false_virginica],
                           [false_setosa,false_versicolor,true_virginica]])

In [127]:
confusion_matrix

array([[15,  0,  0],
       [ 0, 15,  0],
       [ 0,  0, 15]])