###### Print Hello World 

In [146]:
#Q1
print('Hello World')

Hello World


In [147]:
#Q2
a=35
b=5
c=a+b
d=a-b
e=a*b
f=a/b
g=a%b

In [148]:
c

40

In [ ]:
d

In [5]:
e

175

In [6]:
f

7.0

In [7]:
g

0

In [ ]:
#Q3
def factorial(num):
    if(num<0):
        return
    if(num==0):
        return 1
    return num*factorial(num-1)

In [145]:
print(factorial(4))

24


In [ ]:
factorial(5)

In [14]:
factorial(6)

720

In [15]:
print(factorial(1))

1


In [16]:
print(factorial(0))

1


In [17]:
print(factorial(-1))

None


In [21]:
a=int(input('Enter the value of a\n'))
b=int(input('Enter the value of b\n'))

Enter the value of a
5
Enter the value of b
27


In [22]:
a

5

In [23]:
b

27

In [ ]:
#Q4
import math
def findAllPrimes(num1,num2):
    if(num1<=1):
        num1=2
    for i in range(num1,num2+1,1 ):
        prime=True
        #print('int value',int(math.sqrt(i)))
        for j in range(2,int(math.sqrt(i))+1,1):
            if(i%j==0):
                prime=False
                break
        if(prime==True):
            print(i)

In [ ]:
findAllPrimes(1,30)

In [ ]:
findAllPrimes(-5,4)

In [ ]:
findAllPrimes(1,100)


In [132]:
#Q5
def LCM(a,b):
    c= a if a>b else b
    for i in range(c,(a*b)+1,1):
        if(i%a==0 and i%b==0):
            print(i)
            break

In [133]:
LCM(2,5)

10


In [ ]:
LCM(5,44)

In [ ]:
#Q6
#Selection sort
list = [7,2,90,1,5]
for i in range(len(list)-1):
    for j in range(len(list)-1):
        if(list[j]<list[j+1]):
            list[j],list[j+1]=list[j+1],list[j]
print(list)

In [2]:
#Q7
import numpy as np
array = np.array([7,2,90,1,5])
for i in range(len(list)-1):
    for j in range(len(list)-1):
        if(list[j]>list[j+1]):
            list[j],list[j+1]=list[j+1],list[j]
print(list)

TypeError: object of type 'type' has no len()

In [152]:
#Q8
m=int(input('Enter value of m'))
n=int(input('Enter value of n'))
matrix1 = np.random.randint(-2,5,size=(m,n))
print(matrix1)

Enter value of m3
Enter value of n4
[[ 1  2 -2  3]
 [-1 -2  1  2]
 [ 4  1  2  2]]


In [3]:
#Q9
import numpy as np
m=int(input('Enter the value of m'))
n=int(input('Enter the value of n'))
p=int(input('Enter the value of p'))
matrix1 = np.random.randint(3,size=(m,n))
matrix2 = np.random.randint(3,size=(n,p))
print('Matrix 1 is :')
print(matrix1)
print('Matrix 2 is :')
print(matrix2)
matrix3 = [[0 for i in range(p)] for j in range(m) ]
print(matrix3)
for i in range(m):
    for j in range(p):
        sum=0
        for k in range(n):
            sum=sum+(matrix1[i,k]*matrix2[k,j])
        matrix3[i][j]=sum
print('resultant matrix :')
print(np.matrix(matrix3))
print('reuslt by inbuilt method')
print(np.dot(matrix1,matrix2))

Enter the value of m3
Enter the value of n3
Enter the value of p3
Matrix 1 is :
[[1 0 1]
 [1 1 0]
 [2 1 1]]
Matrix 2 is :
[[0 1 0]
 [2 1 1]
 [1 0 1]]
[[0, 0, 0], [0, 0, 0], [0, 0, 0]]
resultant matrix :
[[1 1 1]
 [2 2 1]
 [3 3 2]]
reuslt by inbuilt method
[[1 1 1]
 [2 2 1]
 [3 3 2]]


In [185]:
#Q10
import csv
f=open('newCSVFile','w')
writer = csv.writer(f)
writer.writerow([3,4,5])

7